// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20210122183604_Intial")]
    partial class Intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 2,
                            Gender = "Male",
                            Name = "Pippen",
                            Species = "Persian"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 1,
                            Gender = "Female",
                            Name = "May",
                            Species = "Bengal"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 1,
                            Gender = "Female",
                            Name = "Nala",
                            Species = "Siamese"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 3,
                            Gender = "Male",
                            Name = "Niko",
                            Species = "Ragdoll"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 4,
                            Gender = "Female",
                            Name = "Simba",
                            Species = "Maine Coon"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 4,
                            Gender = "Male",
                            Name = "Leith",
                            Species = "Beagle"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 1,
                            Gender = "Female",
                            Name = "Marry",
                            Species = "Poodle"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 6,
                            Gender = "Female",
                            Name = "Nakita",
                            Species = "German Shepherd"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 7,
                            Gender = "Male",
                            Name = "Apollo",
                            Species = "Siberian Husky"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 5,
                            Gender = "Female",
                            Name = "Ava",
                            Species = "German Shepherd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
