// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20210122235830_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Species")
                        .IsRequired();

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = "2",
                            Gender = "Male",
                            Name = "Pippen",
                            Species = "Persian"
                        },
                        new
                        {
                            CatId = 2,
                            Age = "1",
                            Gender = "Female",
                            Name = "May",
                            Species = "Bengal"
                        },
                        new
                        {
                            CatId = 3,
                            Age = "1",
                            Gender = "Female",
                            Name = "Nala",
                            Species = "Siamese"
                        },
                        new
                        {
                            CatId = 4,
                            Age = "3",
                            Gender = "Male",
                            Name = "Niko",
                            Species = "Ragdoll"
                        },
                        new
                        {
                            CatId = 5,
                            Age = "4",
                            Gender = "Female",
                            Name = "Simba",
                            Species = "Maine Coon"
                        },
                        new
                        {
                            CatId = 6,
                            Age = "6",
                            Gender = "Male",
                            Name = "Mittens",
                            Species = "Persian"
                        },
                        new
                        {
                            CatId = 7,
                            Age = "6",
                            Gender = "Female",
                            Name = "Puki",
                            Species = "Bengal"
                        },
                        new
                        {
                            CatId = 8,
                            Age = "1",
                            Gender = "Female",
                            Name = "Jay",
                            Species = "Siamese"
                        },
                        new
                        {
                            CatId = 9,
                            Age = "3",
                            Gender = "Male",
                            Name = "Snuffs",
                            Species = "Ragdoll"
                        },
                        new
                        {
                            CatId = 10,
                            Age = "1",
                            Gender = "Female",
                            Name = "Kinko",
                            Species = "Maine Coon"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Species")
                        .IsRequired();

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = "4",
                            Gender = "Male",
                            Name = "Leith",
                            Species = "Beagle"
                        },
                        new
                        {
                            DogId = 2,
                            Age = "1",
                            Gender = "Female",
                            Name = "Marry",
                            Species = "Poodle"
                        },
                        new
                        {
                            DogId = 3,
                            Age = "6",
                            Gender = "Female",
                            Name = "Nakita",
                            Species = "German Shepherd"
                        },
                        new
                        {
                            DogId = 4,
                            Age = "7",
                            Gender = "Male",
                            Name = "Apollo",
                            Species = "Siberian Husky"
                        },
                        new
                        {
                            DogId = 5,
                            Age = "5",
                            Gender = "Female",
                            Name = "Ava",
                            Species = "German Shepherd"
                        },
                        new
                        {
                            DogId = 6,
                            Age = "4",
                            Gender = "Male",
                            Name = "Link",
                            Species = "Beagle"
                        },
                        new
                        {
                            DogId = 7,
                            Age = "5",
                            Gender = "Female",
                            Name = "Larry",
                            Species = "Poodle"
                        },
                        new
                        {
                            DogId = 8,
                            Age = "7",
                            Gender = "Female",
                            Name = "Tiger",
                            Species = "German Shepherd"
                        },
                        new
                        {
                            DogId = 9,
                            Age = "3",
                            Gender = "Male",
                            Name = "Mr.Pebbles",
                            Species = "Siberian Husky"
                        },
                        new
                        {
                            DogId = 10,
                            Age = "3",
                            Gender = "male",
                            Name = "Rex",
                            Species = "German Shepherd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
